import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/admin/rewards/editreward.module.css";
import { AdminHamburgerMenu, AdminFooter } from "@/components";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import { Button } from "@mui/material";
import { db } from "@/firebase";
import { doc, getDoc } from "firebase/firestore";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export default function RewardLists() {
  const [reward, setReward] = useState();
  const router = useRouter();
  const { id } = router.query;

  useEffect(() => {
    async function getData() {
      const rewardDocRef = doc(db, "business_challenges", id);
      const rewardDocSnap = await getDoc(rewardDocRef);
      setReward(rewardDocSnap.data());
    }

    getData();
  }, [id]);

  return (
    <>
      <Head>
        <title>Rewwardy: Reward Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Images/Rewwardy-Icon.png" />
      </Head>
      <AdminHamburgerMenu className={styles.shapingBar} />
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.container}>
          <div className={styles.header}>
            <h1>{reward?.name}</h1>
          </div>
          <div className={styles.box}>
            <div className={styles.imgcanvas}>
              <Image src={reward?.imageUrl} height={275} width={275}/>
            </div>
            <h2>Description</h2>
            <p>{reward?.description}</p>
            <br />
            <h2>Information</h2>
            <div className={styles.pillgrid}>
              <div className={styles.pill}>
                <h3>Milestone Type</h3>
                <p>{reward?.milestoneType}</p>
              </div>
              <div className={styles.pill}>
                <h3>Milestone Value</h3>
                <p>{reward?.milestoneValue}</p>
              </div>
              <div className={styles.pill}>
                <h3>Valid From</h3>
                <p>{reward?.validFrom}</p>
              </div>
              <div className={styles.pill}>
                <h3>Valid Until</h3>
                <p>{reward?.validUntil}</p>
              </div>
            </div>
          </div>
          <br />
          <div className={styles.btnrow}>
            <Button
              className={styles.btn}
              variant="contained"
              onClick={() => router.push("/admin/dashboard")}
            >
              Go to Dashboard
            </Button>
          </div>
        </div>
      </main>
      <AdminFooter />
    </>
  );
}
