import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/admin/rewards/allrewards.module.css";
import { AdminHamburgerMenu, AdminFooter } from "@/components";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import { Button } from "@mui/material";
import { getCookie } from "cookies-next";
import { db } from "@/firebase";
import { collection, query, where, getDocs } from "firebase/firestore";
import { truncateString } from "@/utils/helpers";
import Link from 'next/link';

const inter = Inter({ subsets: ["latin"] });

export default function RewardLists() {
  const [rewards, setRewards] = useState([]);
  const router = useRouter();

  const businessid = getCookie("businessId");

  useEffect(() => {
    async function getData() {
      const q = query(
        collection(db, "business_rewards"),
        where("businessId", "==", businessid)
      );
      const querySnapshot = await getDocs(q);
      let rewards = [];
      querySnapshot.forEach((doc) => {
        let tempReward = doc.data();
        tempReward.id = doc.id;
        rewards.push(tempReward);
      });
      setRewards(rewards);
    }

    getData();
  }, []);

  return (
    <>
      <Head>
        <title>Rewwardy: View Rewards</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Images/Rewwardy-Icon.png" />
      </Head>
      <AdminHamburgerMenu className={styles.shapingBar} />
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.container}>
          <div className={styles.header}>
            <h1>View Rewards</h1>
          </div>
          <div className={styles.list}>
            {rewards.map((reward, key) => (
              <Link href={`/admin/rewards/${reward.id}`}>
                <div className={styles.reward} key={key}>
                  <div className={styles.rewardrow}>
                    <h2 className={styles.name}>{reward.name}</h2>
                    <p>
                      Valid After: {reward.milestoneValue}{" "}
                      {reward.milestoneType}
                    </p>
                  </div>
                  <div className={styles.rewardrow}>
                    <p style={{ width: "60%" }}>
                      {truncateString(reward?.description, 50)}
                    </p>
                    <p>Valid Until: {reward.validUntil}</p>
                  </div>
                </div>
              </Link>
            ))}
          </div>
          <br />
          <Button
            className={styles.btn}
            variant="contained"
            onClick={() => router.push("/admin/dashboard")}
          >
            Go to Dashboard
          </Button>
        </div>
      </main>
      <AdminFooter />
    </>
  );
}
