import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/admin/rewards/allrewards.module.css";
import Link from "next/link";
import { AdminFooter } from "@/components";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import { Button, TextField } from "@mui/material";
import { getCookie } from "cookies-next";
import { db } from "@/firebase";
import { collection, query, where, getDocs } from "firebase/firestore";
import { truncateString } from "@/utils/helpers";

const inter = Inter({ subsets: ["latin"] });

export default function RewardLists() {
  const [rewards, setRewards] = useState([]);
  const router = useRouter();

  const businessid = getCookie("businessid");
  console.log(businessid);
  useEffect(() => {
    async function getData() {
      const q = query(
        collection(db, "business_rewards"),
        where("businessId", "==", businessid)
      );
      const querySnapshot = await getDocs(q);
      let rewards = [];
      querySnapshot.forEach((doc) => {
        rewards.push(doc.data());
      });
      setRewards(rewards);
    }

    getData();
  }, []);
  return (
    <>
      <Head>
        <title>Rewwardy: Reward Lists</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Images/Rewwardy-Icon.png" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.headerbar}>
          <h2 className={styles.header}>All Rewards</h2>
        </div>
        <br />
        <div className={styles.list}>
          {rewards.map((reward, key) => (
            <div className={styles.reward} key={key}>
              <div className={styles.rewardrow}>
                <p className={styles.name}>{reward.name}</p>
                <p>
                  Valid After: {reward.milestoneValue} {reward.milestoneType}
                </p>
              </div>
              <div className={styles.rewardrow}>
                <p style={{ width: "60%" }}>{truncateString(reward?.description, 50)}</p>
                <p>Valid Until: {reward.validUntil}</p>
              </div>
            </div>
          ))}
        </div>
        <br/>
        <Button className={styles.btn} variant="contained" onClick={() => router.push("/admin/dashboard")}>Go to Dashboard</Button>
      </main>
      <AdminFooter />
    </>
  );
}
