import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/admin/login.module.css'
import Link from "next/link";
import { TopNavbar, Footer } from "../../components";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ['latin'] })


export default function AdminDashboard() {
  return (
    <>
      <Head>
        <title>Rewwardy: Admin Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Images/Rewwardy-Icon.png" />
      </Head>
      <TopNavbar/>
      <main className={`${styles.main} ${inter.className}`}>
        <h2>Login Business</h2>
      </main>
      <Footer />
    </>
  )
}
