import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/admin/login.module.css";
import Link from "next/link";
import { TopNavbar, Footer } from "../../components";
import { useRouter } from "next/router";
import { useState } from "react";
import { Button, TextField } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export default function AdminLogin() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  return (
    <>
      <Head>
        <title>Rewwardy: Admin Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Images/Rewwardy-Icon.png" />
      </Head>
      {/* <TopNavbar/> */}
      <main className={`${styles.main} ${inter.className}`}>
        <h2 className={styles.header}>Login Business</h2>
        <div className={styles.form}>
          <TextField id="standard-basic" label="Email" variant="standard" />
          <br />
          <TextField id="standard-basic" label="Password" variant="standard" />
          <br />
          <Button variant="contained">Login</Button>
        </div>
      </main>
      <Footer />
    </>
  );
}
