import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/admin/rewards/editreward.module.css";
import { HamburgerMenu, Footer } from "@/components";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import { Button } from "@mui/material";
import { db } from "@/firebase";
import { doc, getDoc } from "firebase/firestore";
import { truncateString } from "@/utils/helpers";

const inter = Inter({ subsets: ["latin"] });

export default function RewardLists() {
  const [reward, setReward] = useState();
  const router = useRouter();
  const { id } = router.query;

  useEffect(() => {
    async function getData() {
      const rewardDocRef = doc(db, "user_rewards", id);
      const rewardDocSnap = await getDoc(rewardDocRef);
      let tempReward = rewardDocSnap.data()
      tempReward.id = rewardDocSnap.id;
      setReward(tempReward);
    }

    getData();
  }, [id]);

  return (
    <>
      <Head>
        <title>Rewwardy: Reward Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Images/Rewwardy-Icon.png" />
      </Head>
      <HamburgerMenu className={styles.shapingBar} />
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.container}>
          <div className={styles.header}>
            <h1>Congrats on winning {reward?.name}</h1>
          </div>
          <div className={styles.box}>
            <h3>Description</h3>
            <p>{reward?.description}</p>
            <br />
            <h3>Valid Unitl</h3>
            <p>{reward?.validUntil}</p>
            <br />
            <h3>Reward Code</h3>
            <p style={{ fontSize: '24px'}}>{reward?.id}</p>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
