import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/about.module.css";
import { Footer } from "../components";
import { useRouter } from "next/router";
import { Button, TextField } from "@mui/material";


const inter = Inter({ subsets: ["latin"] });

export default function About() {
    
    const router = useRouter();
 
    return (
    <>
      <Head>
        <title>Rewwardy: About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Images/Rewwardy-Icon.png" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.pictureBox}>
            <img src="/Images/Rewwardy-Icon.png" alt="Rewwardy Icon" className={styles.picture}/>
        </div>
        <div className={styles.row}>
          <h1 className={styles.header}>Rewwardy</h1>
        </div>
        <br/>
        <p className={styles.teammembers}>Songiemar García | Emilio De Jesus | Christian Rosado</p>
        <br/>
        <div className={styles.form}>
            <br/>
            <button
              className={styles.purpleButton}
              id="standard-basic"
              variant="standard"
              onClick={() => router.push("https://youtu.be/EwiUtPBRCUA")}
            >
              Elevator Pitch Video
            </button>
            <br />
            <button
              className={styles.purpleButton}
              id="standard-basic"
              variant="standard"
              onClick={() => router.push("https://www.canva.com/design/DAFzn4PS5xs/8Gauc0ShPuF16YtnNLtdfQ/edit?utm_content=DAFzn4PS5xs&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton ")}
            >
              Presentation Slides
            </button>
            <br />
            <button
              className={styles.purpleButton}
              id="standard-basic"
              variant="standard"
              onClick={() => router.push("https://github.com/sxngie/Rewwardy")}
            >
              GitHub Repository
            </button>
            <br />
            <button
              className={styles.pinkButton}
              id="standard-basic"
              variant="standard"
              onClick={() => router.push("https://rewwardy-capstone.web.app/admin")}
            >
              Admin Login
            </button>
            <br />
            <button
              className={styles.pinkButton}
              id="standard-basic"
              variant="standard"
              onClick={() => router.push("https://rewwardy-capstone.web.app/")}
            >
              User Login
            </button>
          </div>
        </main>
      <Footer />
    </>
  );
}
