import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Challenge.module.css'
import Link from "next/link";
import { HeadTitle, Footer } from "../components";
import HamburgerMenu, { Links } from '../components/HamburgerMenu.js'
import { useRouter } from "next/router";

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  return (
    <>
      <Head>
        <title>Rewwardy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Images/Rewwardy-Icon.png" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className="row">
          <HeadTitle/>
            <HamburgerMenu className={styles.shapingBar}/>
        </div>
        <div className="row">
          <div id = "SectionDiv" className = "column" >
            <div className={styles.pictureFrame}/>
            <h2 className ={styles.sectionHead}>Free Tequila Shot</h2>
            <business className={styles.business}>Off the Wall</business>
            <div className={styles.rewardcard}>
              <div className="row">
              </div>
              <div className="row">
                <rdescription>Visit the bar 10 separate days and spend more than $5 each visit.</rdescription>
                <visits>Visits: 6/10</visits>
              </div>
            </div>
          </div>

          <Link href="/">
            <button
            className={styles.pinkButton}>
              Go Back
            </button>
          </Link>
        </div>
      </main>
      <Footer></Footer>
    </>
  )
}
