import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Challenge.module.css";
import Link from "next/link";
import { Footer } from "../components";
import HamburgerMenu from "../components/HamburgerMenu.js";
import { useState, useEffect } from "react";
import { getCookie } from "cookies-next";
import { db } from "@/firebase";
import {
  collection,
  query,
  where,
  getDocs,
} from "firebase/firestore";

const inter = Inter({ subsets: ["latin"] });

function CardEntity({
  imageSrc,
  title,
  businessName,
  description,
  expDate,
  action,
}) {
  return (
    <div className={styles.cardEntity}>
      <div className={styles.pictureFrame}>
        <img className={styles.picture} src={imageSrc} />
      </div>
      <h2 className={styles.cardLabel}>{title}</h2>
      <h3 className={styles.business}>{businessName}</h3>
      <div className={styles.description}>
        <p>{description}</p>
      </div>
      <Link href="/">
        <button className={styles.pinkButton}>{action}</button>
      </Link>
      <div className={styles.expireDate}>{expDate}</div>
    </div>
  );
}

export default function Challenge() {
  const [user, setUser] = useState();
  const [challenges, setChallenges] = useState([]);
  const [inProgress, setInProgress] = useState([]);

  const userid = getCookie("userid");

  useEffect(() => {
    async function getData() {
      // Fetch User
      const user_query = query(collection(db, "users"), where('authId', '==', userid));
      const userDoc = await getDocs(user_query);
      userDoc.forEach((doc_) => {
        // console.log(doc_.data());
        setUser(doc_.data());
        let challenges_ = [];
        doc_.data()?.businesses.map(async (businessId) => {
        // Queries
        // console.log(businessId);
        const businessRewardQuery = query(
          collection(db, "business_challenges"),
          where("businessId", "==", businessId)
        );
        // Snapshots
        const businessRewardQuerySnapshot = await getDocs(businessRewardQuery);
        businessRewardQuerySnapshot.forEach((doc) => {
          challenges_.push(doc.data());
          // console.log(doc.data());
        });
        setChallenges(challenges_);
      });
      });
      // setUser(userInfo);
    }

    getData();
  }, [userid]);

  return (
    <>
      <Head>
        <title>Rewwardy: Challenges</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Images/Rewwardy-Icon.png" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className="row">
          <h2 className={styles.header}>Challenges</h2>
          <br />
          <HamburgerMenu className={styles.shapingBar} />
        </div>
          <div className="row">
            <div id="SectionDiv" className="column">
              <div className="container">
                {inProgress.length > 0 ? (
                <div className={styles.scrollableContainer}>
                  {challenges.map((challenge) => (
                    <CardEntity
                      imageSrc={challenge?.imageSrc}
                      title={challenge?.name}
                      businessName={challenge?.businessName}
                      description={challenge?.description}
                      expDate={challenge.validUntil}
                      action="More Info"
                      to={`/reward/more-info/${5}`}
                    />
                  ))}
                </div>
              ) : (
                <div className={styles.norewards}>
                  <p>
                    Still haven't started a challenge? Go visit you local shop.
                  </p>
                </div>
              )}
              </div>
            </div>
          </div>
      </main>
      <Footer></Footer>
    </>
  );
}