import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from "next/link";
import { HeadTitle, Footer } from "../components";
import HamburgerMenu, { Links } from '../components/HamburgerMenu.js'
import { useRouter } from "next/router";

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  return (
    <>
      <Head>
        <title>Rewwardy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Images/Rewwardy-Icon.png" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className="row">
          <HeadTitle/>
            <HamburgerMenu className={styles.shapingBar}/>
        </div>
        <div className="row">
          <img
            className={styles.logo}
            src="/Images/Rewwardy-Icon.png"
            alt="Rewwardy Logo"
            width={250}
            height={200}
            priority
          /> 
          <div id = "SectionDiv" className = "column" >
            <h2 className ={styles.sectionHead}>New Challenges</h2>
            <div className={styles.rewardcard}>
              <div className="row">
                <rtitle>Free Muffin</rtitle>
                <business>Friend's Cafe</business>
              </div>
              <div className="row">
                <rdescription>Visit 4 times to get a free muffin.</rdescription>
                <expdate>Valid Until: 10/23/2023</expdate>
              </div>
            </div>
          </div>

          <Link href="/scanner">
            <button
            className={styles.pinkButton}>
              Scan QR
            </button>
          </Link>
        </div>
      </main>
      <Footer></Footer>
    </>
  )
}
