import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/login.module.css";
import Link from "next/link";
import { Footer } from "../components";
import { useRouter } from "next/router";
import { useState } from "react";
import { Button, TextField } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export default function UserLogin() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  return (
    <>
      <Head>
        <title>Rewwardy: Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Images/Rewwardy-Icon.png" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h2 className={styles.header}>Login</h2>
        <br />
        <div className={styles.form}>
          <TextField
            className={styles.inputField}
            id="standard-basic"
            label="Email"
            variant="standard"
          />
          <br />
          <TextField
            className={styles.inputField}
            id="standard-basic"
            label="Password"
            variant="standard"
          />
          <br />
          <Button
            className={styles.clickText}
            id="standard-basic"
            variant="standard"
          >
            Forgot password?
          </Button>
          <br />
          <Button className={styles.pinkButton} variant="contained">
            Submit
          </Button>
          <br />
          <Button
            className={styles.clickText}
            id="standard-basic"
            variant="standard"
          >
            Create an Account
          </Button>
        </div>
      </main>
      <Footer />
    </>
  );
}
