import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Reward.module.css'
import Link from "next/link";
import { Footer } from "../components";
import HamburgerMenu from '../components/HamburgerMenu.js'
import { useRouter } from "next/router";
import fs from 'fs';
import path from 'path';
import { useState } from "react";
import {
  Button,
  Select,
  TextField,
  FormControl,
  InputLabel,
  MenuItem,
} from "@mui/material";
import { db } from "@/firebase";
import { collection, addDoc } from "firebase/firestore";
import { getAuth, createUserWithEmailAndPassword } from "firebase/auth";

const inter = Inter({ subsets: ["latin"] });


function CardEntity({ imageSrc, title, businessName, description, expDate }) {
  return (
      <div className={styles.cardEntity}>
          <div className={styles.pictureFrame}><img id="Reward image"  src={imageSrc} className={styles.picture}/></div> {}
          <h2 className={styles.cardLabel}>{title}</h2>
          <h3 className={styles.business}>{businessName}</h3>
          <div className={styles.description}>
              <p>{description}</p>
          </div>
          <Link href="/">
              <button className={styles.pinkButton}>Redeem</button>
          </Link>
          <div className={styles.expireDate}>{expDate}</div>
      </div>
  );
}


const firstName = 'Linus Tech';
const lastName = 'Tips';
const email = 'LTT@techtips.com';
const phone = '1800helloworld';
const password = 'topSecret';
const dateOfBirth = 'theDaftertomorrow';
const gender = 'Alpha Male';



export default function Home({ cards }) {
  return (
    <>
      <Head>
        <title>Rewwardy: User Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Images/Rewwardy-Icon.png" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.row}>
          <h1 className={styles.header}>User Profile</h1>
          <br/>
            <HamburgerMenu className={styles.shapingBar}/>
        </div>
        <div className={styles.column}>
        <div 
        style={{
            backgroundColor:'white',
            borderRadius:'5px',
            padding: '5px',
            margin: '5px',
            width: '25%'
          }}>
          <div className={styles.form}>
            <TextField
              className={styles.inputField}
              label="First Name"
              variant="standard"
              value={firstName}
              onChange={(e) => setFirstName(e.target.value)}
            />
            <br />
            <TextField
              className={styles.inputField}
              label="Last Name"
              variant="standard"
              value={lastName}
              onChange={(e) => setLastName(e.target.value)}
            />
            <br />
            <TextField
              className={styles.inputField}
              label="Email"
              variant="standard"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
            <br />
            <TextField
              className={styles.inputField}
              label="Phone"
              variant="standard"
              value={phone}
              onChange={(e) => setPhone(e.target.value)}
            />
            <br />
            <TextField
              className={styles.inputField}
              label="Password"
              variant="standard"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
            <br />
            <label className={styles.label}>
              Date of Birth
              <br />
            </label>
            <input
              className={styles.dateinput}
              label="Date of Birth"
              type="date"
              variant="standard"
              value={dateOfBirth}
              onChange={(e) => setDateOfBirth(e.target.value)}
            />
            <br />
            <label className={styles.label}>
              Gender
              <br />
            </label>
            <Select
              className={styles.inputField}
              label="Gender"
              variant="standard"
              value={gender}
              onChange={(e) => setGender(e.target.value)}
            >
              <MenuItem value={"Male"}>Male</MenuItem>
              <MenuItem value={"Female"}>Female</MenuItem>
              <MenuItem value={"Other"}>Other</MenuItem>
              <MenuItem value={"Prefer not to say"}>Prefer not to say</MenuItem>
            </Select>
            <br />
            </div>
            <br />
            <Button
              className={styles.pinkButton}
              variant="contained"
              onClick={() => createUserAccount()}
            >
              Edit
            </Button>
          </div>
        </div>
      </main>
      <Footer />
    </>
  )
}

export async function getStaticProps() {
  const filePath = path.join(process.cwd(), 'public/data', 'cards.json');
  const jsonData = fs.readFileSync(filePath);
  const cards = JSON.parse(jsonData);

  return {
    props: {
      cards,
    },
  };
}