import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Reward.module.css'
import Link from "next/link";
import { HeadTitle, Footer } from "../components";
import HamburgerMenu, { Links } from '../components/HamburgerMenu.js'
import { useRouter } from "next/router";

const inter = Inter({ subsets: ['latin'] })

function CardEntity({ imageSrc, title, businessName, description, expDate }) {
  return (
      <div className={styles.cardEntity}>
          <div className={styles.pictureFrame}><img id="Reward image"  src={imageSrc} className={styles.picture}/></div> {}
          <h2 className={styles.cardLabel}>{title}</h2>
          <h3 className={styles.business}>{businessName}</h3>
          <div className={styles.description}>
              <p>{description}</p>
          </div>
          <Link href="/">
              <button className={styles.pinkButton}>Redeem</button>
          </Link>
          <div className={styles.expireDate}>{expDate}</div>
      </div>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Rewwardy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Images/Rewwardy-Icon.png" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className="row">
            <h1 className={styles.header}>Rewards</h1>
            <br/>
            <HamburgerMenu className={styles.shapingBar}/>
        </div>
        <div className="row">
          <div id = "SectionDiv" className = "column" >
            <div className='container'>
              <div className={styles.scrollableContainer}>
                <CardEntity imageSrc='Props_samples/bubba.jpg' title='8oz Taro Tea' businessName='Bubble Tea Yum' description='One 8oz Taro drink.' expDate='February 8th, 2024'></CardEntity>
                <CardEntity imageSrc='Props_samples/pizza.jpeg' title='Pizza Slice' businessName='Titos Pizza' description='Free cheese pizza slice.' expDate='January 10th, 2024'></CardEntity>
                <CardEntity imageSrc='Props_samples/latte.jpg' title='Latte' businessName='Friends Cafe' description='Free 8oz latte.' expDate='March 18th, 2024'></CardEntity>
                <CardEntity imageSrc='Props_samples/toast.jpg' title='Toast' businessName='Cabra Tosta' description='Two slices of toasts.' expDate='February 2nd, 2024'></CardEntity>
                <CardEntity imageSrc='Props_samples/icecream.jpg' title='Ice Cream Cone' businessName='Rex Cream' description='One regular soft cone.' expDate='April 6th, 2024'></CardEntity>
                <CardEntity imageSrc='Props_samples/cookie.jpeg' title='CC Cookie' businessName='Friends Cafe' description='Chocolate chip cookie.' expDate='March 27th, 2024'></CardEntity>
                <CardEntity imageSrc='Props_samples/latte.jpg' title='Latte' businessName='Shaktea' description='Free 8oz latte.' expDate='January 5th, 2024'></CardEntity>
                </div>
          </div>
          </div>
        </div>
      </main>
      <Footer></Footer>
    </>
  )
}

