import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Reward.module.css'
import Link from "next/link";
import { Footer } from "../components";
import HamburgerMenu, { Links } from '../components/HamburgerMenu.js'
import { useRouter } from "next/router";

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  return (
    <>
      <Head>
        <title>Rewwardy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Images/Rewwardy-Icon.png" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className="row">
            <h2 className={styles.header}>Rewards</h2>
            <br/>
            <HamburgerMenu className={styles.shapingBar}/>
        </div>
        <div className="row">
          <div id = "SectionDiv" className = "column" >
          <div className={styles.pictureFrame}/>
            <h2 className ={styles.sectionHead}>1 Free Muffin</h2>
            <business className={styles.business}>Friend's Cafe</business>
            <div className={styles.rewardcard}>
              <div className="row">
              </div>
              <div className="row">
                <rdescription>You visited the store 10 days in a row, spending $5 each day.</rdescription>
              </div>
            </div>
          </div>

          <Link href="/">
            <button
            className={styles.pinkButton}>
              Reedem
            </button>
          </Link>
        </div>
      </main>
      <Footer></Footer>
    </>
  )
}
