import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Scanner.module.css'
import { HeadTitle, Footer } from "../components";
import Link from "next/link";
import HamburgerMenu, { Links } from '../components/HamburgerMenu.js'

const inter = Inter({ subsets: ['latin'] })

export default function Scanner() {
    return (
        <>
          <Head>
            <title>Rewwardy</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/Images/Rewwardy-Icon.png" />
          </Head>
        <main className={`${styles.main} ${inter.className}`}>
        <div className="row">
            <HeadTitle/>
            <HamburgerMenu className={styles.shapingBar}/>
        </div>
            <div className={styles.camera}>
            </div>
            <Link href="scan">
                <button
                    className={styles.pinkButton}>
                    Scan QR
                </button>
            </Link>
          </main>
          <Footer></Footer>
        </>
    )
}